### ISSUE TITLE
Setup basic Django REST Framework app

### ISSUE THREAD

**Issue by cverna** [fedora-infra/fpdc#1]
Conditions of Satisfaction :

- [x] DRF app boilerplate
- [x] 1 HTTP endpoint available ( maybe something like https://pdc.fedoraproject.org/rest_api/v1/)
- [x] The API should have versioning enabled.
- [x] Django version 1.11 LTS
- [x] DRF version 3.8.2

**Comment by subpop** [comment]
DRF supports a pretty flexible versioning scheme: http://www.django-rest-framework.org/api-guide/versioning/

**Comment by subpop** [comment]
#19 sets up a full model-serializer-viewset-router relationship, and adds router URLs under a namespace-versioned prefix of `api/v1`.

**Comment by cverna** [comment]
Lets close this, thanks
