### ISSUE TITLE
Add GET, POST, PUT and DELETE HTTP method for https://pdc.fedoraproject.org/rest_api/v1/releases/

### ISSUE THREAD

**Issue by cverna** [fedora-infra/fpdc#10]
Conditions of Satisfaction :
- [x] releases endpoint is available
- [x] HTTP GET method is used to get the list of Releases available
- [x] HTTP POST method is used to create a new Release, this method requires authentication
- [x] HTTP PUT method is used to update an existing Release, this method requires authentication
- [x] HTTP DELETE is used to delete an existing Release, this method requires authentication

**Comment by subpop** [comment]
#24 actually enabled `IsAuthenticatedOrReadOnly` permissions for all views by default. This URL routes, methods and authentication requirements are in place. I believe this issue can be closed as well.
