### ISSUE TITLE
Choose a name

### ISSUE THREAD

**Issue by abompard** [fedora-infra/fpdc#12]
The current repo name is fdc, for Fedora Definition Center. Do we want to keep it?

Other suggestions:
* FPDC (Fedora Product Definition Center)
* PDC-lite
* PDC2
* fedora-pdc

I personnaly like FPDC better because Fedora Definition Center seems weird to me, as if it was defining Fedora. But maybe that's just because I'm not a native speaker.

**Comment by cverna** [comment]
Haha I could not find a name and I proposed the same as you except for FPDC (see https://pagure.io/fedora-infrastructure/issue/7239) 

I am fine with FPDC, it will make it more obvious that this is intended to replace PDC.

**Comment by abompard** [comment]
Yeah I copied the list from your email because this question hadn't been adressed yet, and added my suggestion.

If you agree with the FPDC name, please rename the project :-)

**Comment by cverna** [comment]
> Yeah I copied the list from your email because this question hadn't been adressed yet, and added my suggestion.
> 
> If you agree with the FPDC name, please rename the project :-)

Done I did not had the correct admin permission before that.
