### ISSUE TITLE
Releases endpoint (https://pdc.fedoraproject.org/rest_api/v1/releases/) - Database Model

### ISSUE THREAD

**Issue by cverna** [fedora-infra/fpdc#5]
Release specification

Attribute name | Type | Example
-- | -- | --
release_id | string | ‘fedora-28’
short | string | ‘fedora’
version | integer | 28
name | string | ‘Fedora’
release_date | string | “2018-09-03”
eol_date | string | “2018-09-04”
release_type | ReleaseType.short | "development" when today () < release_date"eol" when today() >= eol_date"ga" when  today() > release_date and today() < eol_date
active | boolean | true when release_type is ga
sigkey | string | ‘81b46521’

ReleaseType  specification

Attribute name | Type | Example
-- | -- | --
short | string | ‘ga’
name | string | ‘Release’
suffix | string | ‘-updates-testing’

Condition of Statisfaction:
- [ ] New DRF application created `releases`
- [ ] Release and ReleaseType model done.

**Comment by subpop** [comment]
> release_type | ReleaseType.short | "development" when today () < release_date"eol" when today() >= eol_date"ga" when  today() > release_date and today() < eol_date
-- | -- | --

It sounds like `release_type` should be a computed property on the model, but not persisted in the database. Is that what you were thinking? If that's the case, why is there a separate table for `ReleaseType` at all? Why not make it a string value derived from the computation of `release_date` and `eol_date`?

**Comment by cverna** [comment]
> > release_type | ReleaseType.short | "development" when today () < release_date"eol" when today() >= eol_date"ga" when  today() > release_date and today() < eol_date
> > -- | -- | --
> 
> It sounds like `release_type` should be a computed property on the model, but not persisted in the database. Is that what you were thinking? If that's the case, why is there a separate table for `ReleaseType` at all? Why not make it a string value derived from the computation of `release_date` and `eol_date`?

Hum good point, initially the computed logic was there to populate another property of the Release "status", but I was thinking that we could use the ReleaseType for that which might not work in the end. Looking at the current ReleaseType we have (https://pdc.fedoraproject.org/rest_api/v1/release-types/)
I ll get the Fedora Release Engineering team inputs on that question.

**Comment by subpop** [comment]
Yea, I saw the existing PDC APIs and figured that is the root of the architectural decision here, but from a strictly objective perspective, there doesn't seem to be much reason for the `ReleaseType` to exist as a related object if the foreign key field is a computed property.

**Comment by cverna** [comment]
> Yea, I saw the existing PDC APIs and figured that is the root of the architectural decision here, but from a strictly objective perspective, there doesn't seem to be much reason for the `ReleaseType` to exist as a related object if the foreign key field is a computed property.

So indeed it appears that the ReleaseType model is not really needed, we just have the release_type attribute in the Release model to be a string. We can compute this field but we need to find the correct algorithm to manage the `updates` releases.
