### ISSUE TITLE
Add GET, POST, PUT and DELETE HTTP method for https://pdc.fedoraproject.org/rest_api/v1/release-types/

### ISSUE THREAD

**Issue by cverna** [fedora-infra/fpdc#9]
Conditions of Satisfaction :
- [x] release-types endpoint is available
- [x] HTTP GET method is used to get the list of ReleaseType available
- [x] HTTP POST method is used to create a new ReleaseType, this method requires authentication
- [x] HTTP PUT method is used to update an existing ReleaseType, this method requires authentication
- [x] HTTP DELETE is used to delete an existing ReleaseType, this method requires authentication

**Comment by subpop** [comment]
#19 adds a serializer and viewset for `ReleaseType`. This will create the RESTful paths to the typical CRUD operations. No authentication is in place yet, but with #19 merged, these endpoints should be operational.

**Comment by cverna** [comment]
Lets close this since we moved away from having the ReleaseType endpoint.
